name: kube-state-metrics
title: Kube state metrics
type: infrastructure
icon: prometheus
scalable: false
helm:
  name: prometheus-community
  source: https://prometheus-community.github.io/helm-charts
  chart: prometheus-community/kube-state-metrics
  version: 7.2.2

workloads:
- name: main
  selector:
    matchLabels:
      app.kubernetes.io/instance: '{{service.helm.release}}'
  kind: deployment
  primary: true
  helm:
    labels: labels
    annotations: podAnnotations
  containers:
  - name: kube-state-metrics
    helm:
      resources: resources
      env: env
