name: kube-state-metrics
title: Kube state metrics
type: infrastructure
icon: prometheus
scalable: false
helm:
  name: prometheus-community
  source: https://prometheus-community.github.io/helm-charts
  chart: prometheus-community/kube-state-metrics
  version: 7.2.2
workloads:
- id: main
  kind: deployment
  primary: true
  containers:
  - name: kube-state-metrics

    helm:
      resources: resources
      env: env
  helm:
    labels: labels
    annotations: podAnnotations
